//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Mateus_wcModel", "FK_AuditingDetails_AuditingMaster", "AuditingMaster", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PITFramework.Auditing.AuditingMaster), "AuditingDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PITFramework.Auditing.AuditingDetail), true)]

#endregion

namespace PITFramework.Auditing
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuditingMateus : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuditingMateus object using the connection string found in the 'AuditingMateus' section of the application configuration file.
        /// </summary>
        public AuditingMateus() : base("name=AuditingMateus", "AuditingMateus")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditingMateus object.
        /// </summary>
        public AuditingMateus(string connectionString) : base(connectionString, "AuditingMateus")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuditingMateus object.
        /// </summary>
        public AuditingMateus(EntityConnection connection) : base(connection, "AuditingMateus")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditingDetail> AuditingDetails
        {
            get
            {
                if ((_AuditingDetails == null))
                {
                    _AuditingDetails = base.CreateObjectSet<AuditingDetail>("AuditingDetails");
                }
                return _AuditingDetails;
            }
        }
        private ObjectSet<AuditingDetail> _AuditingDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditingMaster> AuditingMasters
        {
            get
            {
                if ((_AuditingMasters == null))
                {
                    _AuditingMasters = base.CreateObjectSet<AuditingMaster>("AuditingMasters");
                }
                return _AuditingMasters;
            }
        }
        private ObjectSet<AuditingMaster> _AuditingMasters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditingDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditingDetails(AuditingDetail auditingDetail)
        {
            base.AddObject("AuditingDetails", auditingDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditingMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditingMasters(AuditingMaster auditingMaster)
        {
            base.AddObject("AuditingMasters", auditingMaster);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Mateus_wcModel", Name="AuditingDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditingDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditingDetail object.
        /// </summary>
        /// <param name="auditingDetailPK">Initial value of the AuditingDetailPK property.</param>
        public static AuditingDetail CreateAuditingDetail(global::System.Int32 auditingDetailPK)
        {
            AuditingDetail auditingDetail = new AuditingDetail();
            auditingDetail.AuditingDetailPK = auditingDetailPK;
            return auditingDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuditingDetailPK
        {
            get
            {
                return _AuditingDetailPK;
            }
            set
            {
                if (_AuditingDetailPK != value)
                {
                    OnAuditingDetailPKChanging(value);
                    ReportPropertyChanging("AuditingDetailPK");
                    _AuditingDetailPK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuditingDetailPK");
                    OnAuditingDetailPKChanged();
                }
            }
        }
        private global::System.Int32 _AuditingDetailPK;
        partial void OnAuditingDetailPKChanging(global::System.Int32 value);
        partial void OnAuditingDetailPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AuditingMasterFK
        {
            get
            {
                return _AuditingMasterFK;
            }
            set
            {
                OnAuditingMasterFKChanging(value);
                ReportPropertyChanging("AuditingMasterFK");
                _AuditingMasterFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuditingMasterFK");
                OnAuditingMasterFKChanged();
            }
        }
        private Nullable<global::System.Int32> _AuditingMasterFK;
        partial void OnAuditingMasterFKChanging(Nullable<global::System.Int32> value);
        partial void OnAuditingMasterFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColumnName
        {
            get
            {
                return _ColumnName;
            }
            set
            {
                OnColumnNameChanging(value);
                ReportPropertyChanging("ColumnName");
                _ColumnName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ColumnName");
                OnColumnNameChanged();
            }
        }
        private global::System.String _ColumnName;
        partial void OnColumnNameChanging(global::System.String value);
        partial void OnColumnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldValue
        {
            get
            {
                return _OldValue;
            }
            set
            {
                OnOldValueChanging(value);
                ReportPropertyChanging("OldValue");
                _OldValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldValue");
                OnOldValueChanged();
            }
        }
        private global::System.String _OldValue;
        partial void OnOldValueChanging(global::System.String value);
        partial void OnOldValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewValue
        {
            get
            {
                return _NewValue;
            }
            set
            {
                OnNewValueChanging(value);
                ReportPropertyChanging("NewValue");
                _NewValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewValue");
                OnNewValueChanged();
            }
        }
        private global::System.String _NewValue;
        partial void OnNewValueChanging(global::System.String value);
        partial void OnNewValueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Mateus_wcModel", "FK_AuditingDetails_AuditingMaster", "AuditingMaster")]
        public AuditingMaster AuditingMaster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditingMaster>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingMaster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditingMaster>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingMaster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AuditingMaster> AuditingMasterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditingMaster>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingMaster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AuditingMaster>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingMaster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Mateus_wcModel", Name="AuditingMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditingMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditingMaster object.
        /// </summary>
        /// <param name="auditingMasterPK">Initial value of the AuditingMasterPK property.</param>
        public static AuditingMaster CreateAuditingMaster(global::System.Int32 auditingMasterPK)
        {
            AuditingMaster auditingMaster = new AuditingMaster();
            auditingMaster.AuditingMasterPK = auditingMasterPK;
            return auditingMaster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuditingMasterPK
        {
            get
            {
                return _AuditingMasterPK;
            }
            set
            {
                if (_AuditingMasterPK != value)
                {
                    OnAuditingMasterPKChanging(value);
                    ReportPropertyChanging("AuditingMasterPK");
                    _AuditingMasterPK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuditingMasterPK");
                    OnAuditingMasterPKChanged();
                }
            }
        }
        private global::System.Int32 _AuditingMasterPK;
        partial void OnAuditingMasterPKChanging(global::System.Int32 value);
        partial void OnAuditingMasterPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TableName
        {
            get
            {
                return _TableName;
            }
            set
            {
                OnTableNameChanging(value);
                ReportPropertyChanging("TableName");
                _TableName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TableName");
                OnTableNameChanged();
            }
        }
        private global::System.String _TableName;
        partial void OnTableNameChanging(global::System.String value);
        partial void OnTableNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TableNameFK
        {
            get
            {
                return _TableNameFK;
            }
            set
            {
                OnTableNameFKChanging(value);
                ReportPropertyChanging("TableNameFK");
                _TableNameFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TableNameFK");
                OnTableNameFKChanged();
            }
        }
        private Nullable<global::System.Int32> _TableNameFK;
        partial void OnTableNameFKChanging(Nullable<global::System.Int32> value);
        partial void OnTableNameFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operation
        {
            get
            {
                return _Operation;
            }
            set
            {
                OnOperationChanging(value);
                ReportPropertyChanging("Operation");
                _Operation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operation");
                OnOperationChanged();
            }
        }
        private global::System.String _Operation;
        partial void OnOperationChanging(global::System.String value);
        partial void OnOperationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServerName
        {
            get
            {
                return _ServerName;
            }
            set
            {
                OnServerNameChanging(value);
                ReportPropertyChanging("ServerName");
                _ServerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServerName");
                OnServerNameChanged();
            }
        }
        private global::System.String _ServerName;
        partial void OnServerNameChanging(global::System.String value);
        partial void OnServerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SessionToken
        {
            get
            {
                return _SessionToken;
            }
            set
            {
                OnSessionTokenChanging(value);
                ReportPropertyChanging("SessionToken");
                _SessionToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SessionToken");
                OnSessionTokenChanged();
            }
        }
        private global::System.String _SessionToken;
        partial void OnSessionTokenChanging(global::System.String value);
        partial void OnSessionTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserFK
        {
            get
            {
                return _UserFK;
            }
            set
            {
                OnUserFKChanging(value);
                ReportPropertyChanging("UserFK");
                _UserFK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserFK");
                OnUserFKChanged();
            }
        }
        private global::System.String _UserFK;
        partial void OnUserFKChanging(global::System.String value);
        partial void OnUserFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RelatedEntityPK
        {
            get
            {
                return _RelatedEntityPK;
            }
            set
            {
                OnRelatedEntityPKChanging(value);
                ReportPropertyChanging("RelatedEntityPK");
                _RelatedEntityPK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RelatedEntityPK");
                OnRelatedEntityPKChanged();
            }
        }
        private Nullable<global::System.Int32> _RelatedEntityPK;
        partial void OnRelatedEntityPKChanging(Nullable<global::System.Int32> value);
        partial void OnRelatedEntityPKChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Mateus_wcModel", "FK_AuditingDetails_AuditingMaster", "AuditingDetail")]
        public EntityCollection<AuditingDetail> AuditingDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditingDetail>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditingDetail>("Mateus_wcModel.FK_AuditingDetails_AuditingMaster", "AuditingDetail", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
